export const text = [
	'the quick brown fox jumps over the lazy dog the sun rises in the east and sets in the west every morning the birds sing their cheerful songs',
	'the river flows calmly through the valley the tall trees sway gently in the breeze the mountains stand tall and majestic against the clear blue sky',
	'a gentle rain falls softly on the green fields the flowers bloom in a riot of colors the city is bustling with people going about their daily lives',
	'the train chugs along the tracks the cat sleeps peacefully on the windowsill the child plays happily in the park the ocean waves crash against the shore',
	'the stars twinkle brightly in the night sky the wind whispers through the leaves of the trees the fire crackles in the fireplace the snow falls silently',
	'covering the ground in a blanket of white the car speeds down the highway the dog barks loudly at the passing cars the clock ticks steadily marking',
	'the passage of time the plane soars high above the clouds the computer hums quietly on the desk the phone rings sharply breaking the silence',
	'the book lies open on the table the lamp casts a warm glow in the room the music plays softly in the background the coffee is brewing in the kitchen',
	'the keys jingle in the pocket the chair creaks as it is moved across the floor the shoes squeak on the polished wood the door opens slowly with a quiet creak',
	'the refrigerator hums steadily in the corner the television is on but no one is watching the microwave beeps signaling the food is ready the pen rolls off',
	'the edge of the desk the notebook is filled with neat handwriting the calendar hangs on the wall marked with important dates the picture frame holds',
	'a photo of a happy memory the mirror reflects the room perfectly the rug is soft underfoot the window is slightly open letting in a cool breeze',
	'the pillow is fluffed and ready for sleep the blanket is warm and comforting the bed is made with clean sheets the closet is full of clothes',
	'the shoes are neatly lined up by the door the bag is packed and ready to go the suitcase is by the door waiting for the trip the ticket is in hand ready',
	'to be used the passport is safely tucked away the map is spread out on the table the sun is shining brightly outside the birds are chirping in the trees',
	'the flowers are in full bloom the grass is green and freshly cut the sky is clear and blue the clouds are white and fluffy the air is fresh and clean',
	'the trees are tall and green the road stretches out ahead the car is ready to go the engine purrs smoothly the wheels turn steadily the radio plays',
	'a familiar tune the scenery passes by in a blur the destination is getting closer the excitement builds as the journey continues the adventure is just beginning',
];